name: on manual trigger

on:
  workflow_dispatch:
    inputs:

jobs:
  generate_burndown_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i
      - name: Generate burndown chart
        uses: ./
        with:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DB_BACKLOG: 231c684795fd49aeb387e41110c2af83
          NOTION_DB_SPRINT_SUMMARY: f762582562d34d6e8e2e4b89050c09be
          NOTION_DB_DAILY_SUMMARY: ef4f661300064ee48a907a3d1348767b
          NOTION_PROPERTY_SPRINT: Sprint
          NOTION_PROPERTY_ESTIMATE: Estimate
          NOTION_PROPERTY_PATTERN_STATUS_EXCLUDE: Completed
      - name: Commit burndown chart
        run: |
          git config --local user.email "ting.szeying@gmail.com"
          git config --local user.name "szenius"
          git add ./out
          git commit -m "run: upload new burndown chart"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
